name: Arctern-bot Release Doc

# This workflow is triggered on pushes or pull request to the repository.
on:
  release:
    types: [published]
  push:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'arctern-docs/**'
      - 'docker/**'
      - '.github/workflows/**'
      - '!**.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run bot realease
        run: |
          docker build --tag arctern-docs:bot-release . --file ./docker/Dockerfile
          docker run -v ${GITHUB_WORKSPACE}:/arctern-docs arctern-docs:bot-release
          git clone https://.:${{ secrets.PUSH_TOKEN }}@github.com/beautifulpython/arctern-docs.git y && tree -d . && \
          cd y && \
          tree -d .
