name: SCALA-TEST

# This workflow is triggered on pushes or pull request to the repository.
on:
  push:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'arctern-docs/**'
      - 'docker/**'
      - '.github/workflows/**'
      - '!**.md'
  pull_request:
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'arctern-docs/**'
      - '.github/workflows/**'
      - '!**.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Run scala test
        run: |
          docker build --tag arctern-docs:1804 . --file ./docker/Dockerfile
          docker run -v ${GITHUB_WORKSPACE}:/arctern-docs arctern-docs:1804
